[cursor]
blink_interval = 200
blink_timeout = 0
thickness = 0.4

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12.0

[font.bold]
family = "Agave Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Agave Nerd Font"
style = "Italic"

[font.normal]
family = "Agave Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/themes/rose-pine-dimmed.toml"
]
