# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#a5a2c8"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#1f1d2e"
red = "#e8547e"
green = "#31748f"
yellow = "#f4b45a"
blue = "#85c3ce"
magenta = "#b18bdf"
cyan = "#e3a19e"
white = "#524f67"

[colors.bright]
black = "#23233a"
red = "#f4b45a"
green = "#31748f"
yellow = "#6e6a86"
blue = "#a5a2c8"
magenta = "#a5a2c8"
cyan = "#85c3ce"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
